require("prototypes.entities.harvester-heavy")
require("prototypes.entities.harvester-light")
require("prototypes.entities.harvester-plasma")
require("prototypes.entities.flying-bot-temp")
require("prototypes.entities.pipes")