require("prototypes.entities.silo")
require("prototypes.entities.landing-pad")
require("prototypes.entities.harvester")
require("prototypes.entities.flying-bot-temp")
require("prototypes.entities.pipes")
require("prototypes.entities.plasma-thruster")